openapi: 3.0.1
info:
  title: 海漂APP后端API
  description: 海漂APP后端API
  contact:
    email: haipiao.dev@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'https://virtserver.swaggerhub.com/HaiPiaoAPP/test/1.0.0'
tags:
  - name: Verified
    description: 完成开发并已验证
  - name: Developped
    description: 已经完成开发
  - name: Developing
    description: 正在开发
  - name: Todo
    description: 未开发
paths:
  /security-code:
    get:
      tags:
        - Developped
      summary: 获取一个验证码（3.1）
      description: |
        客户端为当前用户设备请求一个验证码，请求中需包含当前设备（手机）号码。服务器端返回一个6位验证码，一分钟内有效。
      parameters:
        - name: cell
          in: query
          description: 请求验证码的手机号
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: string
                  security_code:
                    type: integer
                  error_message:
                    type: string
              examples:
                success:
                  value:
                    status_code: SUCCESS
                    security_code: 098320
                to many requests:
                  value:
                    status_code: THROTTLED
                    error_message: Too many requests
                external SMS service failure:
                  value:
                    status_code: EXTERNAL_SERVICE_ERROR
                    error_message: SMS server denied request
                internal server error:
                  value:
                    status_code: INTERNAL_SERVER_ERROR
                    error_message: Internal server error.
        default:
          description: 任何非200状态码即为请求失败，按照INTERNAL_SERVER_ERROR处理
  /security-code/verification:
    post:
      tags:
        - Developped
      summary: 验证验证码
      description: |
        客户端请求服务器验证 1. 用户登陆（`login`）或 2. 用户注册（`registration`）或 3. 用户修改手机号（`update_cell`），请求中需包含当前用户手机号码。服务器端需完成验证码验证，如果验证类型为1（用户注册）， 服务端需为请求中的手机号码创建一个新的账户， 如果账户已存在需返回相应错误码。服务器端需返回一个session token。
      requestBody:
        description: 验证码信息包括：1. 请求验证码的手机号（`cell`）2. 验证码类型（`type`） 3. 验证码 (`code`)
        content:
          application/json:
            schema:
              type: object
              properties:
                cell:
                  type: string
                  example: '8888888'
                type:
                  type: string
                  example: registration
                code:
                  type: string
                  example: '314489'
        required: true
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: string
                  data:
                    type: object
                    properties:
                      seesion_token:
                        type: string
                      issued_time:
                        type: number
              examples:
                sucess:
                  value:
                    status_code: SUCCESS
                    seesion_token: 'euMA3jBRShPn/K935B9e0A==:T4p4tBPdDrgD70UbbgGNoQ=='
                    issued_time: 1571641196070
                invalid security code:
                  value:
                    status_code: UNAUTHORIZED
                    error_message: invalid security code
                internal server error:
                  value:
                    status_code: INTERNAL_SERVER_ERROR
                    error_message: Internal server error.
        default:
          description: 任何非200状态码即为请求失败，按照INTERNAL_SERVER_ERROR处理
  /image/getsecuritytoken:
    get:
      tags:
        - Todo
      summary: 获取上传图片的security token
      description: 获取将图片上传OSS的secuiriy token。Secuiry token有效期为30分钟。
      parameters:
        - name: Cookie
          in: header
          description: 必须包含`seesion_token`。不支持`visitor mode`(游客模式)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                required:
                  - status_code
                  - endpoint
                  - access_key_id
                  - access_key_secret
                  - security_token
                  - expire_time
                type: object
                properties:
                  status_code:
                    type: string
                  error_message:
                    type: string
                  data:
                    type: object
                    properties:
                      endpoint:
                        type: string
                        description: 阿里云OSS服务的endpoint
                      access_key_id:
                        type: string
                        description: 阿里云OSS服务的AccessKeyId
                      access_key_secret:
                        type: string
                        description: 阿里云OSS服务的AccessKeySecret
                      security_token:
                        type: string
                        description: 阿里云OSS服务的SecurityToken
                      expire_time:
                        type: string
                        description: Security token的过期时间。以epoch time开始计算，精度为秒。
              examples:
                success:
                  value:
                    status_code: SUCCESS
                    data:
                      endpoint: http://oss-cn-hangzhou.aliyuncs.com
                      access_key_id: tempaccesskey
                      access_key_secret: someaccesskeysecret
                      security_token: sometoken
                      expire_time: 1573113573
                unauthorized:
                  value:
                    status_code: UNAUTHORIZED
                    error_message: Need to log in
                internal server error:
                  value:
                    status_code: INTERNAL_SERVER_ERROR
                    error_message: Internal server error
  /image/updaload:
    post:
      tags:
        - Todo
      summary: 创建图片链接
      description: |
        先调用阿里云的OSS服务上传图片，获取返回的url，再调用该API创建一个图片链接。图片类型：1. 文章中图片（`in_article`）2. 头像图片 （`profile`）。
      parameters:
        - name: Cookie
          in: header
          description: 必须包含`seesion_token`。不支持`visitor mode`(游客模式)
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
                - image_type
                - image_url
              type: object
              properties:
                image_type:
                  type: string
                  example: profile
                image_url:
                  type: string
                  format: uri
                  example: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/myphoto.jpg
        required: true
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: string
                  image_id:
                    type: integer
              examples:
                success:
                  value:
                    status_code: SUCCESS
                    image_id: 1234
                invalid image url:
                  value:
                    status_code: BAD_REQUEST
                    error_message: invalid image url
                internal server error:
                  value:
                    status_code: INTERNAL_SERVER_ERROR
                    error_message: Internal server error.
        default:
          description: 任何非200状态码即为请求失败，按照INTERNAL_SERVER_ERROR
  /user:
    post:
      tags:
        - Todo
      summary: 创建一个新用户
      description: 创建一个新用户。用于用户注册流程中。
      parameters:
        - name: Cookie
          in: header
          description: 必须包含`seesion_token`（临时session token。当完成验证码验证后，服务器返回一个临时session token）。该token在此次使用后即失效，客户端再后续的请求中应该在`Cookie`中加入该次请求响应中返回的`seesion_token`字段
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
                - birthday
                - cell
                - gender
                - name
              type: object
              properties:
                name:
                  type: string
                  example: 王小明
                gender:
                  type: string
                  enum:
                    - F
                    - M
                    - U
                birthday:
                  type: string
                  example: 1992/01/31
                cell:
                  type: string
                  example: '8888888'
                profile_image_url:
                  type: string
                  format: uri
                  example: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/myphoto.jpg
        required: true
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                required:
                  - status_code
                type: object
                properties:
                  status_code:
                    type: string
                  error_message:
                    type: string
                  data:
                    required:
                      - id
                      - session_token
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 100001
                      session_token:
                        type: string
                        example: 'euMA3jBRShPn/K935B9e0A==:T4p4tBPdDrgD70UbbgGNoQ=='
              examples:
                success:
                  value:
                    status_code: SUCCESS
                    id: 1234
                    session_token: 'euMA3jBRShPn/K935B9e0A==:T4p4tBPdDrgD70UbbgGNoQ=='
                missing required field:
                  value:
                    status_code: BAD_REQUEST
                    error_message: Missing required fields in user creation request
                internal server error:
                  value:
                    status_code: INTERNAL_SERVER_ERROR
                    error_message: Internal server error.
      x-codegen-request-body-name: 用户信息
  /category:
    get:
      tags:
        - Todo
      summary: 获取"分类"列表
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum:
              - hot
              - all
              - misc
        - name: Cookie
          in: header
          description: 包含`seesion_token`。如果缺失，则为`visitor mode`(游客模式)
          schema:
            type: string
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                required:
                  - data
                type: object
                properties:
                  sucess:
                    type: boolean
                  data:
                    type: object
                    properties:
                      hot:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 100012
                            name:
                              type: string
                              example: 学校
                            cover_image_url:
                              type: string
                              format: uri
                              example: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/school.jpg
                      all:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 100012
                            name:
                              type: string
                              example: 工作
                            cover_image_url:
                              type: string
                              format: uri
                              example: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/work.jpg
                      misc:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 100012
                            name:
                              type: string
                              example: 旅游
                            cover_image_url:
                              type: string
                              format: uri
                              example: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/travel.jpg
              examples:
                success-all:
                  value:
                    status_code: SUCCESS
                    data:
                      all:
                        - id: 11
                          name: 工作
                          cover_image_url: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/work.jpg
                        - id: 12
                          name: 旅游
                          cover_image_url: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/travel.jpg
                success-hot:
                  value:
                    status_code: SUCCESS
                    data:
                      hot:
                        - id: 11
                          name: 工作
                          cover_image_url: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/work.jpg
                success-misc:
                  value:
                    status_code: SUCCESS
                    data:
                      misc:
                        - id: 12
                          name: 旅游
                          cover_image_url: aliyun-abc.oss-cn-hangzhou.aliyuncs.com/abc/travel.jpg
                bad request:
                  value:
                    status_code: BAD_REQUEST
                    error_message: invalid query parameter
                internal server error:
                  value:
                    status_code: INTERNAL_SERVER_ERROR
                    error_message: Internal server error
  /user/category:
    post:
      tags:
        - Todo
      summary: 添加用户关注的"分类"
      description: 添加用户关注的"分类"。每个分类由一个integer类型的id唯一识别。
      parameters:
        - name: Cookie
          in: header
          description: 必须包含`seesion_token`。不支持`visitor mode`(游客模式)
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
                - categories
              type: object
              properties:
                categories:
                  type: array
                  items:
                    type: integer
            example:
              categories:
                - 11
                - 12
        required: true
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                required:
                  - status_code
                type: object
                properties:
                  status_code:
                    type: string
                  error_message:
                    type: string
              examples:
                success:
                  value:
                    status_code: SUCCESS
                unauthorized:
                  value:
                    status_code: UNAUTHORIZED
                    error_message: Need to log in
                bad request:
                  value:
                    status_code: BAD_REQUEST
                    error_message: Invalid category
                internal server error:
                  value:
                    status_code: INTERNAL_SERVER_ERROR
                    error_message: Internal server error
components:
  schemas:
    ErrorInfo:
      required:
        - error
      type: object
      properties:
        seccess:
          type: boolean
          example: false
        error:
          required:
            - error_code
          type: object
          properties:
            error_code:
              type: string
              example: INTERNAL_SERVER_ERROR
            error_message:
              type: string
              example: vender service denied request
